#+title: Ch05
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Using Structs to Structure Related Data

https://doc.rust-lang.org/book/ch05-00-structs.html

Just like in some other programming languages a struct(ure) is a data type that
packages or groups together a few related values (possibly of different types)
into a container.

** Structs - Definition and Initialization


An exemplary `User` structure.

#+begin_src

struct User {
    active: bool,
    username: String,
    email: String,
    sign_in_count: u64,
}

#+end_src

An exemplary initialization of `User` structure (the fields don't have to be
initialized in the order in which they are in the definition).

#+begin_src

fn main() {
    let user1 = User {
        active: true,
        username: String::from("name1"),
        email: String::from("email1@example.com"),
        sign_in_count: 1,
    };
}

#+end_src

To get a value from a field use a dot syntax.

#+begin_src

fn main() {
    let user1 = User {
        active: true,
        username: String::from("name1"),
        email: String::from("email1@example.com"),
        sign_in_count: 1,
    };

    println!("The user1:");
    println!("\tname:{}", user1.username);
    println!("\temail:{}", user1.email);
    println!("\tis_active:{}", user1.active);
    println!("\tsign_in_count:{}", user1.sign_in_count);
}

#+end_src

To change any value a user (whole user, not just some fields) must be mutable.

#+begin_src

fn main() {
    let mut user1 = User {
        active: true,
        username: String::from("name1"),
        email: String::from("email1@example.com"),
        sign_in_count: 1,
    };

    println!("The user1:");
    println!("\tname:{}", user1.username);
    println!("\temail:{}", user1.email);
    println!("\tis_active:{}", user1.active);
    println!("\tsign_in_count:{}", user1.sign_in_count);

    println!("\n--Changing user1 data.--\n");
    user1.email = String::from("email1.1@example.com");

    println!("The user1:");
    println!("\tname:{}", user1.username);
    println!("\temail:{}", user1.email);
    println!("\tis_active:{}", user1.active);
    println!("\tsign_in_count:{}", user1.sign_in_count);
}

#+end_src

We may write an initializer function for a user:

#+begin_src

fn init_user(email: String, username: String) -> User {
    User {
        active: true,
        username: username,
        email: email,
        sign_in_count: 1,
    }
}

fn main() {
    let user2 = init_user("name2".to_string(), "email2@example.com".to_string());

    println!("The user2:");
    println!("\tname:{}", user2.username);
    println!("\temail:{}", user2.email);
    println!("\tis_active:{}", user2.active);
    println!("\tsign_in_count:{}", user2.sign_in_count);
}

#+end_src

*** Field Init Shorthand

#+begin_src

fn init_user(email: String, username: String) -> User {
    User {
        active: true,
        username, // cause the field and fn argument got the same name
        email,    // cause the field and fn argument got the same name
        sign_in_count: 1,
    }
}

fn main() {
    let user2 = init_user("name2".to_string(), "email2@example.com".to_string());

    println!("The user2:");
    println!("\tname:{}", user2.username);
    println!("\temail:{}", user2.email);
    println!("\tis_active:{}", user2.active);
    println!("\tsign_in_count:{}", user2.sign_in_count);
}

#+end_src

*** Struct Update Syntax

This syntax is used to create a struct, the one that is almost identical to the
existing one.

#+begin_src

fn print_user_data(user: User) {
    println!(
        "User({}, {}, {}, {})",
        user.active, user.username, user.email, user.sign_in_count,
    );
}

fn main() {
    let mut user1 = init_user("name1".to_string(), "email1@example.com".to_string());
    let mut user2 = User {
        email: "email2@example.com".to_string(),
        username: "name2".to_string(),
        ..user1
    };

    user1.sign_in_count = 2;
    user2.active = false;

    print!("user1:\t");
    print_user_data(user1);

    print!("user2:\t");
    print_user_data(user2);
}

#+end_src

which prints:

#+begin_src

user1:	User(true, email1@example.com, name1, 2)
user2:	User(false, name2, email2@example.com, 1)

}

#+end_src

* Next To Read
https://doc.rust-lang.org/book/ch05-01-defining-structs.html#creating-instances-with-struct-update-syntax
