#+title: Ch05
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Using Structs to Structure Related Data

https://doc.rust-lang.org/book/ch05-00-structs.html

Just like in some other programming languages a struct(ure) is a data type that
packages or groups together a few related values (possibly of different types)
into a container.

** Structs - Definition and Initialization


An exemplary `User` structure.

#+begin_src

struct User {
    active: bool,
    username: String,
    email: String,
    sign_in_count: u64,
}

#+end_src

An exemplary initialization of `User` structure (the fields don't have to be
initialized in the order in which they are in the definition).

#+begin_src

fn main() {
    let user1 = User {
        active: true,
        username: String::from("name1"),
        email: String::from("email1@example.com"),
        sign_in_count: 1,
    };
}

#+end_src

To get a value from a field use a dot syntax.

#+begin_src

fn main() {
    let user1 = User {
        active: true,
        username: String::from("name1"),
        email: String::from("email1@example.com"),
        sign_in_count: 1,
    };

    println!("The user1:");
    println!("\tname:{}", user1.username);
    println!("\temail:{}", user1.email);
    println!("\tis_active:{}", user1.active);
    println!("\tsign_in_count:{}", user1.sign_in_count);
}

#+end_src

To change any value a user (whole user, not just some fields) must be mutable.

#+begin_src

fn main() {
    let mut user1 = User {
        active: true,
        username: String::from("name1"),
        email: String::from("email1@example.com"),
        sign_in_count: 1,
    };

    println!("The user1:");
    println!("\tname:{}", user1.username);
    println!("\temail:{}", user1.email);
    println!("\tis_active:{}", user1.active);
    println!("\tsign_in_count:{}", user1.sign_in_count);

    println!("\n--Changing user1 data.--\n");
    user1.email = String::from("email1.1@example.com");

    println!("The user1:");
    println!("\tname:{}", user1.username);
    println!("\temail:{}", user1.email);
    println!("\tis_active:{}", user1.active);
    println!("\tsign_in_count:{}", user1.sign_in_count);
}

#+end_src

We may write an initializer function for a user:

#+begin_src

fn init_user(username: String, email: String) -> User {
    User {
        active: true,
        username: username,
        email: email,
        sign_in_count: 1,
    }
}

fn main() {
    let user2 = init_user("name2".to_string(), "email2@example.com".to_string());

    println!("The user2:");
    println!("\tname:{}", user2.username);
    println!("\temail:{}", user2.email);
    println!("\tis_active:{}", user2.active);
    println!("\tsign_in_count:{}", user2.sign_in_count);
}

#+end_src

*** Field Init Shorthand

#+begin_src

fn init_user(username: String, email: String) -> User {
    User {
        active: true,
        username, // cause the field and fn argument got the same name
        email,    // cause the field and fn argument got the same name
        sign_in_count: 1,
    }
}

fn main() {
    let user2 = init_user("name2".to_string(), "email2@example.com".to_string());

    println!("The user2:");
    println!("\tname:{}", user2.username);
    println!("\temail:{}", user2.email);
    println!("\tis_active:{}", user2.active);
    println!("\tsign_in_count:{}", user2.sign_in_count);
}

#+end_src

*** Struct Update Syntax

This syntax is used to create a struct, the one that is almost identical to the
existing one.

#+begin_src

fn print_user_data(user: User) {
    println!(
        "User({}, {}, {}, {})",
        user.active, user.username, user.email, user.sign_in_count,
    );
}

fn main() {
    let mut user1 = init_user("name1".to_string(), "email1@example.com".to_string());
    let mut user2 = User {
        email: "email2@example.com".to_string(),
        username: "name2".to_string(),
        ..user1
    };

    user1.sign_in_count = 2;
    user2.active = false;

    print!("user1:\t");
    print_user_data(user1);

    print!("user2:\t");
    print_user_data(user2);
}

#+end_src

which prints:

#+begin_src

user1:	User(true, email1@example.com, name1, 2)
user2:	User(false, name2, email2@example.com, 1)

}

#+end_src

Note, the `..user1` must come last.

Note that the struct update syntax uses `=` like an assignment (because it moves
data). If we commented the line:

#+begin_src

username: "name2".to_string(),

#+end_src

the code would not compile.

#+BEGIN_QUOTE

In this example, we can no longer use `user1 ` after creating `user2` because
the `String` in the `username` field of `user1` was moved into `user2`. If we
had given `user2` new `String` values for both `email` and `username`, and thus
only used the `active` and `sign_in_count` values from `user1`, then `user1`
would still be valid after creating `user2`. Both `active` and `sign_in_count`
are types that implement the `Copy` trait, so the behavior we discussed in the
“Stack-Only Data: Copy” section would apply. We can also still use `user1.email`
in this example, because its value was not moved out of `user1`.

#+END_QUOTE

*** Tuple Structs

Tuple Structs are structs that resemble tuples (the don't have names associated
with the fields, only types):

#+begin_src

struct Color(i32, i32, i32);
struct Point(i32, i32, i32);

fn main() {
let black = Color(0, 0, 0);
let origin = Point(0, 0, 0);

}

#+end_src

`Color` and `Point` are different types (although they take 3 `i32` each). For
that reason a function that takes a `Point` cannot accept a `Color`.

Tuple Structs can be destructured (similar to tuples) and indexed using `.` and
a number (similar to tuples), e.g.

#+begin_src

let Point(x, y, z) = origin; // destructuring
println!("x: {}, y: {}, z: {}", x, y, z);

#+end_src

prints:

#+begin_src

x: 0, y: 0, z: 0

#+end_src

*** Unit-Like Structs

An unit-like struct has no fields (similar to `()`). They are useful to
implement a trait on a type that doesn't store data in it.

#+begin_src

struct AlwaysEqual; // unit-like struct

fn main() {
    let subject = AlwaysEqual;
}

#+end_src

** Ownership of Structs

Previously, in `User` struct, we used `String`s for some field names. Thanks to
this the struct owns its data. It is possible to use `&str` instead. In that
case the struct does not own the data, but points to the data owned by something
else. To write `User` with `&str` however we need to use `lifetimes` covered in
Chapter 10 (otherwise, we are likely to get an compilation error).

* Example Program with Structs

A Program for calculating the area of a rectangle.

Take 1 (no structs):

#+begin_src

fn get_rectangle_area(width: u32, height: u32) -> u32 {
    width * height
}

fn main() {
    let width1 = 30;
    let height1 = 50;

    println!(
        "The area of the rectangle is {} square pixels.",
        get_rectangle_area(width1, height1)
    );
}

#+end_src

Here, we had to use the function name `get_rectangle_area` to indicate that the
parameters (`width` and `height`) are related.

Take 2 (no structs):

#+begin_src

fn get_rectangle_area(dimensions: (u32, u32)) -> u32 {
    dimensions.0 * dimensions.1
}

fn main() {
    let rect1 = (30, 50);

    println!(
        "The area of the rectangle is {} square pixels.",
        get_rectangle_area(rect1)
    );
}

#+end_src

Tuple adds a bit of structure, but the elements in a tuple are not named,
moreover swapping elements of a tuple (here `width` and `height`) may sometimes
cause an error (although here it makes no difference).

Take 3 (structs):

#+begin_src

struct Rectangle {
    width: u32,
    height: u32,
}

fn get_area(rectangle: &Rectangle) -> u32 {
    rectangle.width * rectangle.height
}

fn main() {
    let rect1 = Rectangle {
        width: 30,
        height: 50,
    };

    println!(
        "The area of the rectangle is {} square pixels.",
        get_area(&rect1)
    );
}

#+end_src

*** Adding Traits


Right now we cannot print an instance of our Rectangle class.

#+begin_src

struct Rectangle {
    width: u32,
    height: u32,
}

fn main() {
    let rect1 = Rectangle {
        width: 30,
        height: 50,
    };

    println!("rect1 is {}", rect1);
}

#+end_src

The code above returns something like:

#+begin_src

// snip

12 |     println!("rect1 is {}", rect1);
   |                        --   ^^^^^ `Rectangle` cannot be formatted with the default formatter
   |                        |
   |                        required by this formatting parameter
   |
help: the trait `std::fmt::Display` is not implemented for `Rectangle`

// snip

#+end_src

This is because by default `{}` inside of `pritnln!` uses a `Display`
formatting. The `Display` formatting (or `Display` trait) is not defined by
default to `Rectangle` (and other structs), since it is not 100% clear how the
user would like to print any possible configuration of its fields.

Unfortunately it (`Rectangle`) doesn't also implement (by default) the `Debug`
trait. So a quick fix with `println!("rect1 is {:?}", rect1);` or even
`println!("rect1 is {:#?}", rect1);` will not work.

To fix it we quickly add the suggested by compiler's error message
`#[derive(Debug)]` just before the struct name:

#+begin_src

#[derive(Debug)]
struct Rectangle {
    width: u32,
    height: u32,
}

fn main() {
    let rect1 = Rectangle {
        width: 30,
        height: 50,
    };

    println!("rect1 is {:#?}", rect1);
}

#+end_src

Now we get a printout (`{:?}` - for `Debug` printout, `{:#?}` - for pretty
`Debug` printout).

An alternative to `{:#?}` would be to use `dbg!` macro. Since it takes the
ownership of an expression, prints to `stderr` and returns the value of the
expression. For that reason it is usually called in the form: `dbg!(&rect1)`:

#+begin_src

#[derive(Debug)]
struct Rectangle {
    width: u32,
    height: u32,
}

fn main() {
    let rect1 = Rectangle {
        width: 30,
        height: 50,
    };

    dbg!(&rect1);
}

#+end_src

Later on we'll learn about other traits and how to implement their custom
behaviors.

* Next To Read
https://doc.rust-lang.org/book/ch05-03-method-syntax.html
