#+title: Ch03
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Common Programming Concepts

https://doc.rust-lang.org/book/ch03-00-common-programming-concepts.html

* Variables and Mutability

By default variables are immutable. Once you declare them with let you cannot
reassign a value to them.

#+begin_src

fn main() {
    let x = 5;
    println!("The value of x is: {x}");
    x = 6; // error, you cannot reassign
    println!("The value of x is: {x}");
}

#+end_src

If you want to change the value in the future label it with 'mut' word during
declaration.

#+begin_src

fn main() {
    let mut x = 5; // type inference, i32, by default
    println!("The value of x is: {x}");
    x = 6; // reassigning, no problem
    println!("The value of x is: {x}");
}

#+end_src

* Constants

You declare constants with 'const' keyword. They cannot change, they can be
declared in any scope, the cannot be followed with 'mut'.

Constants may be set only to a constant expression, not the result of a value
that could only be computed at runtime.

They are named with all uppercase and underscores.

#+begin_src

const SECS_IN_HOUR: u32 = 60 * 60; // must have type declaration

#+end_src

They are valid for the entire time a program runs (within the scope in which
they are declared).

* Shadowing

You can declare (with 'let') a new variable with the same name as the one that
already exists. In such a case you got shadowing (compare with Ch02.
Programming a Guessing Game).

Example:

#+begin_src

fn main() {
    let x = 5;
    println!("The value of x is: {x}");

    let x = 6;
    println!("The value of x is: {x}");
}

#+end_src
