#+title: Ch03
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Common Programming Concepts

https://doc.rust-lang.org/book/ch03-00-common-programming-concepts.html

** Variables and Mutability

By default variables are immutable. Once you declare them with let you cannot
reassign a value to them.

#+begin_src

fn main() {
    let x = 5;
    println!("The value of x is: {x}");
    x = 6; // error, you cannot reassign
    println!("The value of x is: {x}");
}

#+end_src

If you want to change the value in the future label it with 'mut' word during
declaration.

#+begin_src

fn main() {
    let mut x = 5; // type inference, i32, by default
    println!("The value of x is: {x}");
    x = 6; // reassigning, no problem
    println!("The value of x is: {x}");
}

#+end_src

*** Constants

You declare constants with 'const' keyword. They cannot change, they can be
declared in any scope, the cannot be followed with 'mut'.

Constants may be set only to a constant expression, not the result of a value
that could only be computed at runtime.

They are named with all uppercase and underscores.

#+begin_src

const SECS_IN_HOUR: u32 = 60 * 60; // must have type declaration

#+end_src

They are valid for the entire time a program runs (within the scope in which
they are declared).

*** Shadowing

You can declare (with 'let') a new variable with the same name as the one that
already exists. In such a case you got shadowing (compare with Ch02.
Programming a Guessing Game).

Example:

#+begin_src

fn main() {
    let x = 5;
    println!("The value of x is: {x}");

    let x = 6;
    println!("The value of x is: {x}");
}

#+end_src

If you omit 'let' (e.g. by mistake) you will get an error.

Another example:

#+begin_src

fn main() {
    let x = 5;
    println!("The value of x is: {x}");

    {
        let x = 6;
        println!("The value of x is: {x}");
    }

    println!("Again, the value of x is: {x}");
}

#+end_src

Thanks to shadowing we can change the type of a variable, example:

#+begin_src

fn main() {
    let spaces: &str = "    ";
    println!("The value of spaces is: '{spaces}'");

    let spaces: usize = spaces.len();
    println!("The value of spaces is: '{spaces}'");
}

#+end_src

But if we use 'mut' keyword then the type stays on and we get an error.

#+begin_src

fn main() {
    let mut spaces: &str = "    ";
    println!("The value of spaces is: '{spaces}'");

    // or
    // spaces = spaces.len();
    spaces: usize = spaces.len();
    println!("The value of spaces is: '{spaces}'");
}

#+end_src

But this is OK:

#+begin_src

fn main() {
    let mut spaces: &str = "    ";
    println!("The value of spaces is: '{spaces}'");

    spaces = "zzz";
    println!("The value of spaces is: '{spaces}'");
}

#+end_src

And that is OK (we'll get a warning about unused 'mut' though):

#+begin_src

fn main() {
    let mut spaces: &str = "    ";
    println!("The value of spaces is: '{spaces}'");

    let spaces: usize = spaces.len();
    println!("The value of spaces is: '{spaces}'");
}

#+end_src

** Data Types

Every value in Rust got a certain data type as Rust is a statically typed
language. It got, however, type inference.

The type inference does not always work, e.g.

#+begin_src

let guess = "42".parse().expect("Not a number!");
println!("The value of guess is: '{guess}");

#+end_src

As here '42' could be parsed as 'u32', 'i32', 'f32', etc. (different type of
ints/floats). Therefore, you need to help the compiler with:

#+begin_src

let guess: u32 = "42".parse().expect("Not a number!");
println!("The value of guess is: '{guess}");

#+end_src

or

#+begin_src

let guess = "42".parse::<f32>().expect("Not a number!");
println!("The value of guess is: '{guess}");

#+end_src

*** Scalar Types

Four primary scalar types: integers (i8, i16, i32, i64, i128, and u8, u16, etc.,
and isize/usize), floating-point numbers (f32, f64), Booleans ('bool' with
'true' or 'false'), and characters ('char' - 4 bytes in size, represents Unicode
characters).

'i32' is a default integer in Rust, 'f64' is a default float, 'isize' and
'usize' depend on the computer architecture and are use for indexing.

You can write '1000' or '1_000'.
