#+title: Ch03
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Common Programming Concepts

https://doc.rust-lang.org/book/ch03-00-common-programming-concepts.html

** Variables and Mutability

By default variables are immutable. Once you declare them with let you cannot
reassign a value to them.

#+begin_src

fn main() {
    let x = 5;
    println!("The value of x is: {x}");
    x = 6; // error, you cannot reassign
    println!("The value of x is: {x}");
}

#+end_src

If you want to change the value in the future label it with 'mut' word during
declaration.

#+begin_src

fn main() {
    let mut x = 5; // type inference, i32, by default
    println!("The value of x is: {x}");
    x = 6; // reassigning, no problem
    println!("The value of x is: {x}");
}

#+end_src

*** Constants

You declare constants with 'const' keyword. They cannot change, they can be
declared in any scope, the cannot be followed with 'mut'.

Constants may be set only to a constant expression, not the result of a value
that could only be computed at runtime.

They are named with all uppercase and underscores.

#+begin_src

const SECS_IN_HOUR: u32 = 60 * 60; // must have type declaration

#+end_src

They are valid for the entire time a program runs (within the scope in which
they are declared).

*** Shadowing

You can declare (with 'let') a new variable with the same name as the one that
already exists. In such a case you got shadowing (compare with Ch02.
Programming a Guessing Game).

Example:

#+begin_src

fn main() {
    let x = 5;
    println!("The value of x is: {x}");

    let x = 6;
    println!("The value of x is: {x}");
}

#+end_src

If you omit 'let' (e.g. by mistake) you will get an error.

Another example:

#+begin_src

fn main() {
    let x = 5;
    println!("The value of x is: {x}");

    {
        let x = 6;
        println!("The value of x is: {x}");
    }

    println!("Again, the value of x is: {x}");
}

#+end_src

Thanks to shadowing we can change the type of a variable, example:

#+begin_src

fn main() {
    let spaces: &str = "    ";
    println!("The value of spaces is: '{spaces}'");

    let spaces: usize = spaces.len();
    println!("The value of spaces is: '{spaces}'");
}

#+end_src

But if we use 'mut' keyword then the type stays on and we get an error.

#+begin_src

fn main() {
    let mut spaces: &str = "    ";
    println!("The value of spaces is: '{spaces}'");

    // or
    // spaces = spaces.len();
    spaces: usize = spaces.len();
    println!("The value of spaces is: '{spaces}'");
}

#+end_src

But this is OK:

#+begin_src

fn main() {
    let mut spaces: &str = "    ";
    println!("The value of spaces is: '{spaces}'");

    spaces = "zzz";
    println!("The value of spaces is: '{spaces}'");
}

#+end_src

And that is OK (we'll get a warning about unused 'mut' though):

#+begin_src

fn main() {
    let mut spaces: &str = "    ";
    println!("The value of spaces is: '{spaces}'");

    let spaces: usize = spaces.len();
    println!("The value of spaces is: '{spaces}'");
}

#+end_src

** Data Types

Every value in Rust got a certain data type as Rust is a statically typed
language. It got, however, type inference.

The type inference does not always work, e.g.

#+begin_src

let guess = "42".parse().expect("Not a number!");
println!("The value of guess is: '{guess}");

#+end_src

As here '42' could be parsed as 'u32', 'i32', 'f32', etc. (different type of
ints/floats). Therefore, you need to help the compiler with:

#+begin_src

let guess: u32 = "42".parse().expect("Not a number!");
println!("The value of guess is: '{guess}");

#+end_src

or

#+begin_src

let guess = "42".parse::<f32>().expect("Not a number!");
println!("The value of guess is: '{guess}");

#+end_src

*** Scalar Types

Four primary scalar types: integers (i8, i16, i32, i64, i128, and u8, u16, etc.,
and isize/usize), floating-point numbers (f32, f64), Booleans ('bool' with
'true' or 'false'), and characters ('char' - 4 bytes in size, represents Unicode
characters).

'i32' is a default integer in Rust, 'f64' is a default float, 'isize' and
'usize' depend on the computer architecture and are use for indexing.

You can write '1000' or '1_000'.

*** Compound Types

**** Tuples

#+begin_src

fn main() {
    let tup: (i32, f64, u8) = (500, 6.4, 1);

    let (x, y, z) = tup; // destructuring tuple

    let first_elt = tup.0;
    let last_elt = tup.2;

    println!("The contents of tup is: '{tup:?}'");
    println!("The value of y is: '{y}'");
    println!("The first_elt and the last_elt are: '{first_elt}' and '{last_elt}'");
}

#+end_src

**** Array

Exemplary code:

#+begin_src

fn main() {
    // allocated on the stack, fixed num of elements
    let a = [1, 2, 3, 4, 5]; // [i32; 5]
    let b: [i32; 3] = [10, 20, 30];
    let c = [1; 3]; // init value; num elts in array, [i32; 3]
    let first_elt = a[0]; // i32

    println!("The arr a contents are: '{a:?}'");
    println!("The arr b contents are: '{b:?}'");
    println!("The arr c contents are: '{c:?}'");
    println!("The arr a first element is: '{first_elt}'");
}

#+end_src

Output:

#+begin_src

The arr a contents are: '[1, 2, 3, 4, 5]'
The arr b contents are: '[10, 20, 30]'
The arr c contents are: '[1, 1, 1]'
The arr a first element is: '1'

#+end_src

Arrays need to have known size. Use it if the number of elements will not need
to change. Otherwise go with a vector (it may shirnk and grow in size on
demand). In Rust arrays are checked for boundaries and an error may be produced.

** Functions

Function (and variable) names are written with 'snake_case'. To define a
function you use a 'fn' keyword. The entry of a program is 'main' function. The
order (before or after its first usage) of a function declaration does not
matter, e.g. both:

#+begin_src

fn main() {
    println!("main function");
    another_function();
}

fn another_function() {
    println!("another function");
}

#+end_src

and

#+begin_src

fn another_function() {
    println!("another function");
}

fn main() {
    println!("main function");
    another_function();
}

#+end_src>

work equally well.

*** Parameters

Parameters and returned values from the function must be always explicitly
provided (unless there is no return value).

#+begin_src

fn print_value_and_label(value: i32, unit_label: char) {
    println!("The measurement is: {value} [{unit_label}].");
}

fn main() {
    println!("main function");
    print_value_and_label(5, 'h');
}

#+end_src

*** Statements and Expressions

Statements are instructions that perform some action and do not return a value.

Expressions evaluate to a resultant value.

Statements end with ';' (semicolon).

'let' (variable declarations) is a statement, '{}' (blocks of code) - are for
expressions.

#+begin_src

fn main() {
    // let x = 6; // statement, OK
    // let x = (let y = 6); // not OK, you cannot chain statements
    let x = {
        let y = 1;
        y + 1
    }; // OK, {} is an expression that returns its last line value
    println!("x is {x}");
}

#+end_src

*** Return Values

We declare a return value from a function with '->', but customarily we don't
use a 'return' keyword (although we may).

#+begin_src

fn get_five() -> i32 {
    5 // no semicolon, because it's an expression
}

fn main() {
    let x = get_five();

    println!("The value of x is: {x}")
}

#+end_src

Or

#+begin_src

fn get_five() -> i32 {
    return 5; // semicolon, not sure why?
}

fn main() {
    let x = get_five();

    println!("The value of x is: {x}")
}

#+end_src

Or

#+begin_src

fn add_one(x: i32) -> i32 {
    x + 1
}

fn main() {
    let x = add_one(2);

    println!("The value of x is: {x}")
}

#+end_src

But ';' after '1' gives an error.

#+begin_src

fn add_one(x: i32) -> i32 {
    x + 1; // error
}

fn main() {
    let x = add_one(2);

    println!("The value of x is: {x}")
}

#+end_src

Here, in 'x + 1;' the semicolon makes it a statement. It ('add_one') returns a
'()' unit value, so we got a type mismatch.

** Comments

A comment starts with two slashes ('//') and continues till the end of the line.

** Control Flow

Here, we got standard 'if'-'else' blocks, that rely on true/false values (no
truthy/falsy).

No 'elif', you type 'else if condition { what to do }'.
