#+title: Ch04
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Understanding Ownership

https://doc.rust-lang.org/book/ch04-00-understanding-ownership.html

Ownership is a unique feature of rust. It allows to make memory safety
guarantees without needing a garbage collector. Ownership is a set of rules that
govern how a Rust program manages memory. If any of the rules are violated, the
program won't compile.

** The Stack and the Heap

Both the stack and the heap are parts of memory available to a program at
runtime.

Stack contains data of well defined size and operates based on LIFO (last in,
first out) rule. Data with unknown size at compile time or a size that might
change must be stored on the heap instead.

Heap is less organized. A certain amount of space in memory is reserved and a
pointer to it is returned (and put on the stack). We call this allocation of
memory (pushing values onto the stack is not considered allocation).

In general the stack is faster and the heap is slower and got some overhead.

The ownership deals with the heap, i.e. keeping track of data on the heap,
minimizing the amount of duplicate data, and cleaning the unused data.

This and/or following section/s will be dealing a lot with strings (as they are
located on the heap).

The data types covered so far (Chapter 3) are of known size, can be stored on
stack.

** Ownership Rules

Each value has an owner.

There can only be one owner at a time.

When the owner goes out of scope, the value will be dropped.

** Variable Scope

#+begin_src

{
    // beginning of scope, no visibility cause no declaration
    let s = "hello"; // string literal, beginning of visibility
                     // string literals are hard-coded into the text of a program
} // end of scope, end of visibility and validity

#+end_src

** The String Type

'String' is an example of data type that is stored on the heap.

String literals (see the 'let s' from the code snippet above) are immutable and
must be known at compile time. The above is not good for the data provided by
the user, hence we got the 'String' type.

Creation of 'String', from string literal:

#+begin_src

let s = String::from("hello");

#+end_src

To do that, we use a function 'from' that acts on a 'String' type, hence the
'::' operator (kind of like class/static method).

Now we can mutate that string.

#+begin_src

fn main() {
    let mut s = String::from("hello");
    println!("{s}");
    s.push_str(", world!");
    println!("{s}");
}

#+end_src
