#+title: Ch04
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Understanding Ownership

https://doc.rust-lang.org/book/ch04-00-understanding-ownership.html

Ownership is a unique feature of rust. It allows to make memory safety
guarantees without needing a garbage collector. Ownership is a set of rules that
govern how a Rust program manages memory. If any of the rules are violated, the
program won't compile.

** The Stack and the Heap

Both the stack and the heap are parts of memory available to a program at
runtime.

Stack contains data of well defined size and operates based on LIFO (last in,
first out) rule. Data with unknown size at compile time or a size that might
change must be stored on the heap instead.

Heap is less organized. A certain amount of space in memory is reserved and a
pointer to it is returned (and put on the stack). We call this allocation of
memory (pushing values onto the stack is not considered allocation).

In general the stack is faster and the heap is slower and got some overhead.

The ownership deals with the heap, i.e. keeping track of data on the heap,
minimizing the amount of duplicate data, and cleaning the unused data.

This and/or following section/s will be dealing a lot with strings (as they are
located on the heap).

The data types covered so far (Chapter 3) are of known size, can be stored on
stack.

** Ownership Rules

Each value has an owner.

There can only be one owner at a time.

When the owner goes out of scope, the value will be dropped.

** Variable Scope

#+begin_src

{
    // beginning of scope, no visibility cause no declaration
    let s = "hello"; // string literal, beginning of visibility
                     // string literals are hard-coded into the text of a program
} // end of scope, end of visibility and validity

#+end_src

** The String Type

'String' is an example of data type that is stored on the heap.

String literals (see the 'let s' from the code snippet above) are immutable and
must be known at compile time. The above is not good for the data provided by
the user, hence we got the 'String' type.

Creation of 'String', from string literal:

#+begin_src

let s = String::from("hello");

#+end_src

To do that, we use a function 'from' that acts on a 'String' type, hence the
'::' operator (kind of like class/static method).

Now we can mutate that string.

#+begin_src

fn main() {
    let mut s = String::from("hello");
    println!("{s}");
    s.push_str(", world!");
    println!("{s}");
}

#+end_src

** Memory and Allocation

For string literals the amount of memory is known in advance and it does not
change (immutability) hence we allocate it on the stack.

The 'String' is allocated on the heap since memory must be requested (allocated)
and freed at runtime.

We request the memory by 'String::from'. The memory is automatically returned
one the variable that owns it goes out of scope:

#+begin_src

{
    let s = String::from("hello");
} // end of scope, the memory allocated for 's' can be returned

#+end_src

At the ending curly bracket ('}') the memory is returned (it is done
automatically, under the hood Rust calls a special function 'drop' that does
that). 'Drop' is a Rust's version of C's 'free'.

a String 's' is composed of three parts (stored on the stack):

- pointer (to the heap where the chars: 'h', 'e', 'l', 'l', 'o' are)
- len - length of the string (dependent on currently used memory)
- capacity - capacity of the string (how many chars can be stored without asking
  for more memory)

If we do something like:

#+begin_src

let s1 = String::from("hello");
let s2 = s1;

#+end_src

Then we copy the data on the stack (pointer, len, capacity) but not on the heap.

When both 's1' and 's2' go out of scope the will both try to free the same
memory (double free is an error).

To ensure memory safety, after 'let s2 = s1;' the 's1' is considered no longer
valid (no need to free anything when 's1' goes out of scope), hence 's1' can no
longer be used.

#+begin_src

fn main() {
    let s1 = String::from("hello");
    let s2 = s1;
    println!("{s1}"); // error, s1 no longer valid, moved to s2
}

#+end_src

's1' is not immediately removed from the stack (in terms of memory cleanup), but
becomes logically invalid (it is treated by compiler as garbage and/or
uninitialized variable).

Rust will never automatically create "deep" copies of data.

** Scope and Assignment

When you assign a completely new value to an existing variable, Rust will call
'drop' and free the original value's memory immediately.

#+begin_src

fn main() {
    let mut s = String::from("hello");
    s = String::from("ahoy"); // String ("hello") is 'dropped'

    println!("{s} world!");
}

#+end_src

Here, 's' exists on the stack all the time (pointer, length, capacity), but
'"hello"' from the heap gets dropped on new assignment.

** Variables and Data Interacting with Clone

'clone' method does a deep copy of 'String' (both the stack and the heap part).

#+begin_src

let s1 = String::from("hello");
let s2 = s1.clone();

println!("s1 = {s1}, s2 = {s2}");

#+end_src

However, using 'clone' is more memory expensive than borrowing.
