#+title: Ch06
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Enums and Pattern Matching

https://doc.rust-lang.org/book/ch06-00-enums.html

`Enums` are for the types that hold a limited number of specific variants.
One of characteristic/famous `enums` is `Option` (it resembles Haskell's `Maybe`
type) that is used to express a value in a container or the total lack of a
value.

Next, we'll see `match` and pattern matching capabilities, which are a handier
alternative to `if let` constructs.

** Defining an Enum

Enums are used to say a value is one of a possible (usually narrow) set of
values, e.g.

#+begin_src

enum IpAddrKind { // types of IP address
    V4,
    V6,
}

#+end_src

and use it like:

#+begin_src

fn main() {
    let ipv4: IpAddrKind = IpAddrKind::V4;
    let ipv6 = IpAddrKind::V6;

    println!("Hello, world!");
}

#+end_src

*** Enum Values

An IP address could be represented using an Enum, Struct mixup:

#+begin_src

enum IpAddrKind {
    V4,
    V6,
}

struct IpAddr {
    kind: IpAddrKind,
    address: String,
}

fn main() {
    let home = IpAddr {
        kind: IpAddrKind::V4,
        address: String::from("127.0.0.1"),
    };

    let loopback = IpAddr {
        kind: IpAddrKind::V6,
        address: String::from("::1"),
    };

    println!("Hello, world!");
}

#+end_src

or Enums alone:

#+begin_src

enum IpAddr {
    V4(String),
    V6(String),
}

fn main() {
    let home = IpAddr::V4(String::from("127.0.0.1"));
    let loopback = IpAddr::V6(String::from("::1"));

    println!("Hello, world!");
}

#+end_src

here `IpAddr::V4()` or `IpAddr::V6()` is a constructor that takes a `String` and
returns an instance of `IpAddr`.

We could also limit the possible values of `IpAddr` even further with:

#+begin_src

enum IpAddr {
    V4(u8, u8, u8, u8),
    V6(String),
}

fn main() {
    let home = IpAddr::V4(127, 0, 0, 1);
    let loopback = IpAddr::V6(String::from("::1"));

    println!("Hello, world!");
}

#+end_src

BTW. Standard library got its own definition of `IpAddr`, see:
https://doc.rust-lang.org/std/net/enum.IpAddr.html (to use it you need to bring
it into scope first, see chapter 7).

Inside of an enum you can have many types, e.g. strings, numeric types, or
structs, e.g.

#+begin_src

enum Message {
    Quit,
    Move { x: i32, y: i32 },
    Write(String),
    ChangeColor(i32, i32, i32),
}

#+end_src

You can also define methods for enums with `impl` (similar to the one in
structs):

#+begin_src

enum Message {
    Quit,
    Move { x: i32, y: i32 },
    Write(String),
    ChangeColor(i32, i32, i32),
}

impl Message {
    fn call(&self) {
        println!("The message says: <<Hi! I'm a message>>.");
    }
}

fn main() {
    let msg = Message::Quit;
    msg.call();
}

#+end_src

which prints:

#+begin_src

The message says: <<Hi! I'm a message>>.

#+end_src

*** The Option Enum

The Option Enum is like Haskell's Maybe. It encodes a value that is something
(alone or with other value inside) or nothing.

Rust doesn't have the null value. In languages that do have it, a variable can
always be null or not-nulll. Still, many consider null to be a mistake
[especially if a null value is used as a not-null value (or in non-null
context)].

The Option Enum is defined like:

#+begin_src

enum Option<T> {
    None,
    Some(T),
}

#+end_src

where `<T>` is a generic type parameter (covered in detail in chapter 10).

and used like:

#+begin_src

let some_number: Option<i32> = Some(1);
let absent_number: Option<i32> = None;
let some_char = Some('a')

#+end_src

`absent_number` need to have the type declaration, otherwise the compiler may
not now if `None` is `Option<i32>` or `Option<char>` or some other `Option`.

You cannot add: `Some(1) + 2` since you're adding different types (`Option<i32>`
and `i32`). You need to extract `i32` from `Option<i32>` (or convert it to
`i32`) first. One way to extract the contents of `Option` is with `pub fn
unwrap_or(self, default: T) -> T`, another option is to use the `match`
expression.

** The match Construct

The `match` construct is used to compare a value against (a) pattern(s).
Different kind of patterns are covered in detail in chapter 19.

An example of pattern matching in action:

#+begin_src

enum Coin {
    Penny,
    Nickel,
    Dime,
    Quarter,
}

fn get_value_in_cents(coin: Coin) -> u8 {
    match coin {
        Coin::Penny => 1, // change 1 to: {println!("a"); 1}, should work OK
        Coin::Nickel => 5,
        Coin::Dime => 10, // change 10 to 'a' for error
        Coin::Quarter => 25, // comment for error (not exhaustive pattern)
    }
}

fn main() {
    let cn = Coin::Dime;
    println!("The value of cn in cents is: {}.", get_value_in_cents(cn));
}

#+end_src

The code in each arm is an expression. All the expressions need to return the
same type of values. The result return from match is decided by the matching
arm.

*** Patterns That Bind to Values

Those patterns are to extract a value from the inside of a struct/object. e.g.

#+begin_src

enum IpAddr {
    V4(String),
    _V6,
}

fn main() {
    let home = IpAddr::V4("127.0.0.1".to_string());
    let addr = match home {
        IpAddr::V4(addr) => addr,
        _ => "unknown".to_string(),
    };

    println!("The IPV4 address is: {}", addr);
}

#+end_src

*** The Option<T> match Pattern

Example:

`find` is to be found here:  https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.find

#+begin_src

fn is_even(n: &i32) -> bool {
    n % 2 == 0
}

fn main() {
    let arr = [1, 2, 3, 4];
    let possible_even = arr.into_iter().find(is_even);

    match possible_even {
        Some(x) => println!("Found even number: {} in arr: {:?}", x, arr),
        None => println!("Didn't find even number in arr: {:?}", arr),
    }
}

#+end_src

which prints:

#+begin_src

Found even number: 2 in arr: [1, 2, 3, 4]

#+end_src

*** Matches Are Exhaustive

A match must cover all possibilities, i.e.

#+begin_src

fn is_even(n: &i32) -> bool {
    n % 2 == 0
}

fn main() {
    let arr = [1, 2, 3, 4];
    let possible_even = arr.into_iter().find(is_even);

    match possible_even {
        Some(x) => println!("Found even number: {} in arr: {:?}", x, arr),
        // no None branch
    }
}

#+end_src

will return a compilation error, since the None branch was not covered.

*** The Catch-All Pattern

#+begin_src

let dice_roll = 1; // [1-6]
    match dice_roll {
        2 => do_something(),
        3 => do_something_else(),
        _ => do_something_else_entirely(),
    }

#+end_src

The `_` is a catch-all pattern. It is placed last since the patterns are
evaluated in order so here it catches (`[1, 4, 5, 6]`).

** If Let and Let Else

The `if let` is a more succint version of `match` on one pattern (and ignoring
the rest), e.g.

#+begin_src

fn main() {
    let dice_roll = 1; // [1-6]
    match dice_roll {
        1 => println!("You rolled 1."),
        _ => (), // does nothing, returns empty tuple, kind of falls through
    }
}

#+end_src

vs.

#+begin_src

fn main() {
    let dice_roll = 1; // [1-6]
    if let 1 == dice_roll {// notic, you got =, and not ==
        println!("You rolled 1.");
    }
}

#+end_src

or

#+begin_src

fn is_even(n: &i32) -> bool {
    n % 2 == 0
}

fn main() {
    let arr = [1, 2, 3];
    let possible_even = arr.into_iter().find(is_even);

    match possible_even {
        Some(x) => println!("Found even number: {}", x),
        _ => (),
    }
}

#+end_src

vs.

#+begin_src

fn is_even(n: &i32) -> bool {
    n % 2 == 0
}

fn main() {
    let arr = [1, 2, 3];
    let possible_even = arr.into_iter().find(is_even);

    if let Some(x) = possible_even {
        println!("Found even number: {}", x)
    }
}

#+end_src


* Next To Read

https://doc.rust-lang.org/book/ch06-03-if-let.html
