#+title: Ch06
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Enums and Pattern Matching

https://doc.rust-lang.org/book/ch06-00-enums.html

`Enums` are for the types that hold a limited number of specific variants.
One of characteristic/famous `enums` is `Option` (it resembles Haskell's `Maybe`
type) that is used to express a value in a container or the total lack of a
value.

Next, we'll see `match` and pattern matching capabilities, which are a handier
alternative to `if let` constructs.

** Defining an Enum

Enums are used to say a value is one of a possible (usually narrow) set of
values, e.g.

#+begin_src

enum IpAddrKind { // types of IP address
    V4,
    V6,
}

#+end_src

and use it like:

#+begin_src

fn main() {
    let ipv4: IpAddrKind = IpAddrKind::V4;
    let ipv6 = IpAddrKind::V6;

    println!("Hello, world!");
}

#+end_src

*** Enum Values

An IP address could be represented using an Enum, Struct mixup:

#+begin_src

enum IpAddrKind {
    V4,
    V6,
}

struct IpAddr {
    kind: IpAddrKind,
    address: String,
}

fn main() {
    let home = IpAddr {
        kind: IpAddrKind::V4,
        address: String::from("127.0.0.1"),
    };

    let loopback = IpAddr {
        kind: IpAddrKind::V6,
        address: String::from("::1"),
    };

    println!("Hello, world!");
}

#+end_src

or Enums alone:

#+begin_src

enum IpAddr {
    V4(String),
    V6(String),
}

fn main() {
    let home = IpAddr::V4(String::from("127.0.0.1"));
    let loopback = IpAddr::V6(String::from("::1"));

    println!("Hello, world!");
}

#+end_src

here `IpAddr::V4()` or `IpAddr::V6()` is a constructor that takes a `String` and
returns an instance of `IpAddr`.

We could also limit the possible values of `IpAddr` even further with:

#+begin_src

enum IpAddr {
    V4(u8, u8, u8, u8),
    V6(String),
}

fn main() {
    let home = IpAddr::V4(127, 0, 0, 1);
    let loopback = IpAddr::V6(String::from("::1"));

    println!("Hello, world!");
}

#+end_src

BTW. Standard library got its own definition of `IpAddr`, see:
https://doc.rust-lang.org/std/net/enum.IpAddr.html (to use it you need to bring
it into scope first, see chapter 7).

Inside of an enum you can have many types, e.g. strings, numeric types, or
structs, e.g.

#+begin_src

enum Message {
    Quit,
    Move { x: i32, y: i32 },
    Write(String),
    ChangeColor(i32, i32, i32),
}

#+end_src


* Next To Read

https://doc.rust-lang.org/book/ch06-01-defining-an-enum.html
